
const ADD_BOARD = 'ADD_BOARD';
const DELETE_BOARD = 'DELETE_BOARD';
const UPDATE_BOARD = 'UPDATE_BOARD';
const UPDATE_CURRENT_BOARD = 'UPDATE_CURRENT_BOARD';

export { ADD_BOARD, DELETE_BOARD, UPDATE_BOARD, UPDATE_CURRENT_BOARD };
